jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.50f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2022.3.50f1
