name: Unity CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      # ✅ Проверяем код из репозитория
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Устанавливаем Unity, активируем лицензию (без .ulf)
      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.50f1
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      # ✅ Сборка проекта для Standalone (Windows, Linux, macOS)
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.50f1
          targetPlatform: StandaloneWindows64  # Можно поменять на StandaloneLinux64, StandaloneOSX

      # ✅ Сохраняем артефакты сборки
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

      # ✅ Деактивация лицензии (необязательно, но рекомендуется)
      - name: Deactivate Unity License
        uses: game-ci/unity-return-license@v2
        if: always()
